### PR TITLE
revised how tablet should be detected, added larger phone detection

### PR DESCRIPTION
**Pull request by serjek**
See discussion at https://forum.starling-framework.org/topic/detect-large-phones-with-devicecapabilities

### CODE REVIEW

**Comment by serjek** [comment]
sure, I just wanted to make it simpler because it's basically copies what happens in screenInchesX/Y

**Comment by joshtynjala** [comment]
It looks like you're forgot to change it back to checking the larger side of the screen.

Actually, I assume that it's intentional, but unfortunately, I cannot accept a breaking change. Please make sure that all functions check the largest size to keep the behavior consistent.

**Comment by serjek** [comment]
Yes, let me explain this PR. Because of new devices recently added to market it is now important to check vs smaller side. 

For example, currently iphone 8+ and iphone X are both detected as tablet because it's larger side is > 5 inches. I can agree at some point that iphone 8+ can be count as tablet (though this is controversial),  but iphone X is not a tablet and not even a hybrid tablet-phone: from device capabilities point of view iphoneX is just a phone like iphone 5s. Exactly this issue is addressed by this PR. 

I added tests for you to compare results. Let me know if I need to add more tests or gather more convincing arguments :)

**Comment by joshtynjala** [comment]
Okay, thanks for the info.  It's very important that the meaning of tabletScreenMinimumInches does not change from checking the larger side because I know that some developers are definitely modifying this value to create custom behavior. I don't want to break their existing code. However, I might be able to to come up with a different solution that checks both the larger and the smaller side so that the iPhone X is correctly detected as a small phone.

**Comment by joshtynjala** [comment]
For my future reference, the following code is useful for checking device dimensions and type in the debugger:

``` actionscript
trace("isTablet:     ", DeviceCapabilities.isTablet(this.stage.starling.nativeStage));
trace("isLargePhone: ", DeviceCapabilities.isLargePhone(this.stage.starling.nativeStage));
trace("isPhone:      ", DeviceCapabilities.isPhone(this.stage.starling.nativeStage));
trace("width:        ", DeviceCapabilities.screenInchesX(this.stage.starling.nativeStage), "inches");
trace("height:       ", DeviceCapabilities.screenInchesY(this.stage.starling.nativeStage), "inches");
```

**Comment by joshtynjala** [comment]
Thanks for looking into this and sharing your findings. I've come up with a solution that checks the dimensions of both sides, which should be more accurate than either of our attempts to use only one side.

The tabletScreenMinimumInches property still applies to the longer side so that developers with legacy code can use it without changes, but I've deprecated this property and replaced it with tabletScreenLandscapeWidthMinimumInches.

I also added tabletScreenPortraitWidthMinimumInches for checking the shorter side. Instead of 4.7 for the default value, I went with 3.5. Some tablets have a much smaller portrait width than the iPad Mini. In particular, early Android tablets that were 600x1024 170 DPI would not be considered tablets if the minimum were 4.7.

I used 2.5 and 4.5 for the large phone minimum dimensions. The iPhone Plus, Pixel XL, and Galaxy Note are all detected as large phones, and I verified that the iPhone X is not detected as a large phone.

To maintain backwards compatibility, isPhone() will still return true for both large and small phones. To specifically detect small phones, you can check `isPhone() && !isLargePhone()`.

**Pull request closed without merging**
